services:
  db:
    container_name: postgres_container
    image: postgres:14.19
    ports:
      - 5000:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-airflow.sql:/docker-entrypoint-initdb.d/init-airflow.sql
    networks:
      - my-network
  af:
    container_name: airflow_container
    image: apache/airflow:3.1.2
    ports:
        - 8000:8080
    env_file:
        - .env
    environment:
        AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes:
        - ./airflow/dags:/opt/airflow/dags
        - ./api-request:/opt/airflow/api-request
    depends_on:
        - db
    networks:
        - my-network
    command: >
        bash -c "airflow db migrate && airflow standalone"
networks:
  my-network:
    driver: bridge
    